name: GitHub Pages

on:                                              
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2                  
      with:
        submodules: true

    - name: Setup Hugo                           
      uses: peaceiris/actions-hugo@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }
        hugo-version: '0.85.0'

    - name: Build                                
      run: hugo --minify

    - name: Deploy                               
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./public
        cname: krischan.dickel.space
